{
    blogs {
        _id
        title
        imageUrl
        text
        author {
            first_name
            last_name
        }
        category {
            title
        }
        comments {
            _id
            user {
                mobile
            }
            comment
            answers {
                _id
                user {
                    mobile
                }
                comment
                show
                createdAt
            }
        }
    }
}
